server.port: 8081

spring:
    application.name: spring-aws-gitlab
    output.ansi.enabled: always
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    h2.console:
        enabled: true
        path: /h2
