stages:
 - build
 - test
 - package

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
  - .m2/repository
  - target

build_job:
 stage: build
 script:
 - echo "Maven compile started"
 - "mvn compile"
test_job:
 stage: test
 script:
 - echo "Maven test started"
 - "mvn test"
package_job:
 stage: package
 artifacts:
  name: api
  paths:
  - target/*.jar
 script:
  - "mvn package"
